#!/bin/bash

function dots() {
    rm -rf "$HOME/.xinitrc" "$HOME/.config/{user-dirs.dirs,user-dirs.locale}"
    stow files
}

function prezto() {
    zsh ./scripts/prezto
}

function rbenv() {
    git clone https://github.com/rbenv/rbenv.git "$HOME/.rbenv"
    mkdir -p "$HOME/.rbenv/plugins"
    git clone https://github.com/rbenv/ruby-build.git "$HOME/.rbenv/plugins/ruby-build"
}

function pyenv() {
    git clone https://github.com/pyenv/pyenv.git "$HOME/.pyenv"
}

function bin() {
    curl -sS https://getcomposer.org/installer | php -- --install-dir="$HOME/bin" --filename=composer
    wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O "$HOME/bin/lein" && chmod +x "$HOME/bin/lein"
    curl -sL https://git.io/JJvpl | bash -
}

function pg() {
    sudo -iu postgres createuser -P -s -e "$USER"
    createdb "$USER"
}

function main() {
    case "$command" in
    dots) dots ;;
    prezto) prezto ;;
    rbenv) rbenv ;;
    pyenv) pyenv ;;
    bin) bin ;;
    pg) pg ;;
    esac
}

command=$1
main "$@"